# Generated by Django 5.2.14 on 2026-07-16 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_unconstrain_chunk_embedding_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('golden_set_fingerprint', models.CharField(max_length=16)),
                ('embedding_model', models.CharField(max_length=100)),
                ('chunk_size', models.IntegerField(blank=True, null=True)),
                ('chunk_overlap', models.IntegerField(blank=True, null=True)),
                ('prefix_enabled', models.BooleanField(default=False)),
                ('hybrid_enabled', models.BooleanField(default=False)),
                ('num_queries', models.IntegerField()),
                ('recall_at_1', models.FloatField()),
                ('recall_at_5', models.FloatField()),
                ('mrr', models.FloatField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'eval_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldenSetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('bucket', models.CharField(choices=[('exact_name', 'Exact name'), ('paraphrase', 'Paraphrase'), ('vague', 'Vague')], max_length=20)),
                ('source', models.CharField(choices=[('uploaded', 'Uploaded'), ('promoted_from_feedback', 'Promoted from feedback')], default='uploaded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookmark')),
            ],
            options={
                'db_table': 'golden_set_entries',
            },
        ),
        migrations.CreateModel(
            name='EvalRunQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text_snapshot', models.TextField()),
                ('expected_bookmark_id_snapshot', models.UUIDField()),
                ('bucket_snapshot', models.CharField(max_length=20)),
                ('found_rank', models.IntegerField(blank=True, null=True)),
                ('eval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='evaluate.evalrun')),
                ('golden_set_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluate.goldensetentry')),
            ],
            options={
                'db_table': 'eval_run_queries',
            },
        ),
        migrations.CreateModel(
            name='SearchFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_rank', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('clicked_bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.bookmark')),
                ('shown_bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.bookmark')),
            ],
            options={
                'db_table': 'search_feedback',
            },
        ),
    ]
