#!/usr/bin/env bash
# =============================================================================
# Bookmark — One-Command Installer
# Usage: bash install.sh
# =============================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[bookmark]${RESET} $*"; }
success() { echo -e "${GREEN}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[!]${RESET} $*"; }
error()   { echo -e "${RED}[✗]${RESET} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}${BLUE}▸ $*${RESET}"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
cat << 'EOF'
  ██████╗  ██████╗  ██████╗ ██╗  ██╗███╗   ███╗ █████╗ ██████╗ ██╗  ██╗
  ██╔══██╗██╔═══██╗██╔═══██╗██║ ██╔╝████╗ ████║██╔══██╗██╔══██╗██║ ██╔╝
  ██████╔╝██║   ██║██║   ██║█████╔╝ ██╔████╔██║███████║██████╔╝█████╔╝
  ██╔══██╗██║   ██║██║   ██║██╔═██╗ ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗
  ██████╔╝╚██████╔╝╚██████╔╝██║  ██╗██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██╗
  ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
EOF
echo -e "${RESET}"
echo -e "  ${CYAN}Open Source · Self-Hosted · Fully Local AI Bookmark Intelligence${RESET}"
echo -e "  ─────────────────────────────────────────────────────────────────\n"

# ── Detect OS ─────────────────────────────────────────────────────────────────
detect_os() {
  case "$(uname -s)" in
    Darwin) echo "macos" ;;
    Linux)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        echo "wsl"
      else
        echo "linux"
      fi
      ;;
    *) error "Unsupported OS: $(uname -s). Bookmark supports macOS, Linux, and WSL2." ;;
  esac
}

OS=$(detect_os)
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_ROOT/.venv"
CLI_TARGET="/usr/local/bin/bookmark"

info "Detected OS: ${BOLD}$OS${RESET}"
info "Install root: ${BOLD}$REPO_ROOT${RESET}"

# ── Dependency checks ─────────────────────────────────────────────────────────
step "Checking dependencies"

require_cmd() {
  if ! command -v "$1" &>/dev/null; then
    error "'$1' is required but not found. $2"
  fi
  success "$1 found ($(command -v "$1"))"
}

require_cmd python3    "Install Python 3.10+ from https://python.org"
require_cmd pip3       "Comes with Python — reinstall Python if missing"
require_cmd node       "Install Node.js 18+ from https://nodejs.org"
require_cmd npm        "Comes with Node.js"
require_cmd psql       "Install PostgreSQL: https://www.postgresql.org/download/"
require_cmd pg_isready "Part of the PostgreSQL client tools"

# Python version check
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
if [[ "$PY_MAJOR" -lt 3 || ("$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 10) ]]; then
  error "Python 3.10+ required, found $PY_VER"
fi
success "Python $PY_VER"

# Node version check
NODE_VER=$(node --version | sed 's/v//')
NODE_MAJOR=$(echo "$NODE_VER" | cut -d. -f1)
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  error "Node.js 18+ required, found $NODE_VER"
fi
success "Node.js $NODE_VER"

# ── Ollama ────────────────────────────────────────────────────────────────────
step "Setting up Ollama"

install_ollama() {
  info "Installing Ollama..."
  if [[ "$OS" == "macos" ]]; then
    if command -v brew &>/dev/null; then
      brew install ollama
    else
      curl -fsSL https://ollama.com/install.sh | sh
    fi
  else
    curl -fsSL https://ollama.com/install.sh | sh
  fi
}

if ! command -v ollama &>/dev/null; then
  warn "Ollama not found — installing automatically"
  install_ollama
else
  success "Ollama found ($(ollama --version 2>/dev/null || echo 'installed'))"
fi

# ── Environment file ──────────────────────────────────────────────────────────
step "Creating environment configuration"

ENV_FILE="$REPO_ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists — skipping (delete it to reconfigure)"
else
  # Generate a random Django secret key
  SECRET_KEY=$(python3 -c "import secrets, string; \
    chars = string.ascii_letters + string.digits + '!@#%^&*(-_=+)'; \
    print(''.join(secrets.choice(chars) for _ in range(50)))")

  cat > "$ENV_FILE" << EOF
# ── Bookmark Environment Configuration ──────────────────────────────────────
# Generated by install.sh on $(date)
# Edit this file to change your configuration.

# Django
DJANGO_SECRET_KEY=$SECRET_KEY
DJANGO_DEBUG=False
DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost

# Database (PostgreSQL)
DB_NAME=bookmark
DB_USER=bookmark
DB_PASSWORD=bookmark_local
DB_HOST=localhost
DB_PORT=5432

# Ports
BOOKMARK_SERVER_PORT=8080
REACT_PORT=8081

# Ollama
OLLAMA_BASE_URL=http://localhost:11434

# Models — fixed for this version, do not change
EMBEDDING_MODEL=nomic-embed-text-v2-moe
GENERATION_MODEL=gemma4:e2b

# Dev mode (set to True to keep temp files for pipeline replay)
BOOKMARK_DEV_MODE=False
EOF
  success ".env created"
fi

# ── Python virtual environment ────────────────────────────────────────────────
step "Setting up Python virtual environment"

if [[ ! -d "$VENV_DIR" ]]; then
  python3 -m venv "$VENV_DIR"
  success "Virtual environment created at .venv/"
else
  success "Virtual environment already exists"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

"$VENV_DIR/bin/pip" install --upgrade pip --quiet
info "Installing Python dependencies into .venv/ (isolated, never touches system Python)..."
"$VENV_DIR/bin/pip" install -r "$REPO_ROOT/requirements.txt" --quiet
success "Python dependencies installed into .venv/"

# ── Node dependencies ─────────────────────────────────────────────────────────
step "Installing Node.js dependencies"

if [[ -f "$REPO_ROOT/frontend/package.json" ]]; then
  cd "$REPO_ROOT/frontend"
  npm install --silent
  PORT=8081 npm run build --silent
  cd "$REPO_ROOT"
  success "Frontend built (port 8081)"
else
  warn "No frontend/package.json found — skipping frontend build"
fi

if [[ -f "$REPO_ROOT/extension/package.json" ]]; then
  info "Building browser extension..."
  cd "$REPO_ROOT/extension"
  npm install --silent

  # Inject the local server port into the extension's config before building
  # The extension needs to know where to POST saved items
  if [[ -f "src/config.ts" ]]; then
    sed -i.bak "s|http://localhost:[0-9]*/|http://localhost:${BOOKMARK_SERVER_PORT:-8080}/|g" src/config.ts
    rm -f src/config.ts.bak
    info "Extension config patched with port ${BOOKMARK_SERVER_PORT:-8080}"
  elif [[ -f "src/config.js" ]]; then
    sed -i.bak "s|http://localhost:[0-9]*/|http://localhost:${BOOKMARK_SERVER_PORT:-8080}/|g" src/config.js
    rm -f src/config.js.bak
    info "Extension config patched with port ${BOOKMARK_SERVER_PORT:-8080}"
  fi

  npm run build --silent
  cd "$REPO_ROOT"

  EXTENSION_DIST="$REPO_ROOT/extension/dist"
  if [[ -d "$EXTENSION_DIST" ]]; then
    success "Browser extension built → $EXTENSION_DIST"
    # Write a small helper file Chrome users can reference
    cat > "$REPO_ROOT/LOAD_EXTENSION.txt" << EXTEOF
How to load the Bookmark browser extension in Chrome
─────────────────────────────────────────────────────
1. Open Chrome and go to:   chrome://extensions
2. Enable "Developer mode"  (toggle, top-right corner)
3. Click "Load unpacked"
4. Select this folder:      $EXTENSION_DIST
5. The Bookmark icon will appear in your Chrome toolbar.

To reload after an update:  run 'bookmark update', then click the
refresh icon on the extension card at chrome://extensions

Extension ID will be shown on the chrome://extensions page.
EXTEOF
    success "Extension load instructions written → LOAD_EXTENSION.txt"
  else
    warn "Build ran but dist/ folder not found — check extension/package.json build script"
  fi
else
  warn "No extension/package.json found — skipping extension build"
fi

# ── PostgreSQL setup ──────────────────────────────────────────────────────────
step "Configuring PostgreSQL"

# Source .env to get DB vars
set -o allexport
# shellcheck disable=SC1091
source "$ENV_FILE"
set +o allexport

wait_for_postgres() {
  local retries=10
  while ! pg_isready -h "$DB_HOST" -p "$DB_PORT" -q; do
    retries=$((retries - 1))
    if [[ "$retries" -le 0 ]]; then
      error "PostgreSQL did not start in time. Is it running?"
    fi
    sleep 1
  done
}

info "Waiting for PostgreSQL..."
wait_for_postgres
success "PostgreSQL is reachable"

# Create DB user and database if they don't exist
psql -U postgres -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" 2>/dev/null \
  | grep -q 1 \
  || psql -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null \
  || warn "Could not create DB user (may already exist or need superuser)"

psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" 2>/dev/null \
  | grep -q 1 \
  || psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null \
  || warn "Could not create database (may already exist)"

# Enable extensions
psql -U postgres -d "$DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;" 2>/dev/null || true
psql -U postgres -d "$DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null \
  || warn "pgvector extension not found — install it: https://github.com/pgvector/pgvector"

success "PostgreSQL database '$DB_NAME' ready"

# ── Django migrations ─────────────────────────────────────────────────────────
step "Running database migrations"

cd "$REPO_ROOT"
python3 manage.py migrate --run-syncdb 2>/dev/null || python3 manage.py migrate
success "Database migrations complete"

# ── Ollama models ──────────────────────────────────────────────────────────────
step "Pulling Ollama models (this may take a few minutes on first run)"

# Start Ollama temporarily to pull models
if ! pgrep -x ollama &>/dev/null; then
  ollama serve &>/dev/null &
  OLLAMA_PID=$!
  sleep 3
  STARTED_OLLAMA=true
fi

pull_model() {
  local model="$1"
  info "Pulling $model..."
  if ollama pull "$model" 2>/dev/null; then
    success "$model ready"
  else
    warn "Could not pull $model — you can pull it manually: ollama pull $model"
  fi
}

pull_model "nomic-embed-text-v2-moe"   # Embedding model (fixed for this version)

pull_model "gemma4:e2b"                # Generation model — tagging & summarisation (fixed)

# Stop the temporary Ollama instance (the service will manage it from now on)
if [[ "${STARTED_OLLAMA:-false}" == "true" ]]; then
  kill "$OLLAMA_PID" 2>/dev/null || true
fi

# ── System service ─────────────────────────────────────────────────────────────
step "Installing Bookmark as a system service"

install_service_linux() {
  local SERVICE_FILE="/etc/systemd/system/bookmark.service"
  local CURRENT_USER
  CURRENT_USER=$(whoami)

  sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=Bookmark — Local AI Bookmark Intelligence
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$REPO_ROOT
EnvironmentFile=$ENV_FILE
ExecStartPre=$REPO_ROOT/scripts/start-ollama.sh
ExecStart=$VENV_DIR/bin/python manage.py runserver 127.0.0.1:\${BOOKMARK_SERVER_PORT}
ExecStop=/bin/kill -TERM \$MAINPID
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bookmark

[Install]
WantedBy=multi-user.target
EOF

  # Separate service for Ollama (if not already a system service)
  if ! systemctl is-enabled ollama &>/dev/null 2>&1; then
    sudo tee /etc/systemd/system/bookmark-ollama.service > /dev/null << EOF
[Unit]
Description=Bookmark — Ollama Local Model Server
After=network.target

[Service]
Type=simple
User=$CURRENT_USER
ExecStart=$(command -v ollama) serve
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bookmark-ollama

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable bookmark-ollama.service
    success "bookmark-ollama service installed"
  fi

  sudo systemctl daemon-reload
  sudo systemctl enable bookmark.service
  success "Systemd service installed and enabled (starts on boot)"
}

install_service_macos() {
  local PLIST_DIR="$HOME/Library/LaunchAgents"
  local PLIST_FILE="$PLIST_DIR/com.bookmark.app.plist"
  local OLLAMA_PLIST="$PLIST_DIR/com.bookmark.ollama.plist"

  mkdir -p "$PLIST_DIR"

  # Parse port from .env
  local PORT=${BOOKMARK_SERVER_PORT:-8080}

  # Main Bookmark service
  cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>com.bookmark.app</string>
  <key>ProgramArguments</key>
  <array>
    <string>$VENV_DIR/bin/python</string>
    <string>$REPO_ROOT/manage.py</string>
    <string>runserver</string>
    <string>127.0.0.1:$PORT</string>
  </array>
  <key>WorkingDirectory</key>  <string>$REPO_ROOT</string>
  <key>EnvironmentVariables</key>
  <dict>
    $(python3 -c "
import re
with open('$ENV_FILE') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            print(f'    <key>{k.strip()}</key><string>{v.strip()}</string>')
    ")
  </dict>
  <key>RunAtLoad</key>         <true/>
  <key>KeepAlive</key>         <true/>
  <key>StandardOutPath</key>   <string>$REPO_ROOT/logs/bookmark.log</string>
  <key>StandardErrorPath</key> <string>$REPO_ROOT/logs/bookmark-error.log</string>
</dict>
</plist>
EOF

  # Ollama service
  cat > "$OLLAMA_PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>com.bookmark.ollama</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(command -v ollama)</string>
    <string>serve</string>
  </array>
  <key>RunAtLoad</key>         <true/>
  <key>KeepAlive</key>         <true/>
  <key>StandardOutPath</key>   <string>$REPO_ROOT/logs/ollama.log</string>
  <key>StandardErrorPath</key> <string>$REPO_ROOT/logs/ollama-error.log</string>
</dict>
</plist>
EOF

  launchctl unload "$PLIST_FILE"    2>/dev/null || true
  launchctl unload "$OLLAMA_PLIST"  2>/dev/null || true
  launchctl load   "$OLLAMA_PLIST"
  launchctl load   "$PLIST_FILE"

  success "LaunchAgent installed — Bookmark starts automatically on login"
}

mkdir -p "$REPO_ROOT/logs"
mkdir -p "$REPO_ROOT/tmp/captures"

# Ollama startup helper script (used by systemd ExecStartPre)
mkdir -p "$REPO_ROOT/scripts"
cat > "$REPO_ROOT/scripts/start-ollama.sh" << 'SCRIPT'
#!/usr/bin/env bash
# Ensure Ollama is running before Bookmark starts
if ! pgrep -x ollama &>/dev/null; then
  ollama serve &>/dev/null &
  sleep 3
fi
SCRIPT
chmod +x "$REPO_ROOT/scripts/start-ollama.sh"

case "$OS" in
  linux|wsl)  install_service_linux ;;
  macos)      install_service_macos ;;
esac

# ── CLI tool ──────────────────────────────────────────────────────────────────
step "Installing 'bookmark' CLI command"

sudo tee "$CLI_TARGET" > /dev/null << CLISCRIPT
#!/usr/bin/env bash
# Bookmark CLI — manage your local Bookmark installation
# Generated by install.sh

REPO_ROOT="$REPO_ROOT"
VENV_DIR="$VENV_DIR"
OS="$OS"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "\${CYAN}[bookmark]\${RESET} \$*"; }
success() { echo -e "\${GREEN}[✓]\${RESET} \$*"; }
warn()    { echo -e "\${YELLOW}[!]\${RESET} \$*"; }
err()     { echo -e "\${RED}[✗]\${RESET} \$*" >&2; exit 1; }

service_cmd() {
  # \$1 = action (start/stop/restart/status)
  local action="\$1"
  case "\$OS" in
    linux|wsl)
      sudo systemctl "\$action" bookmark-ollama 2>/dev/null || true
      sudo systemctl "\$action" bookmark
      ;;
    macos)
      local plist_app="\$HOME/Library/LaunchAgents/com.bookmark.app.plist"
      local plist_ollama="\$HOME/Library/LaunchAgents/com.bookmark.ollama.plist"
      case "\$action" in
        start)
          launchctl load "\$plist_ollama" 2>/dev/null || true
          launchctl load "\$plist_app"
          ;;
        stop)
          launchctl unload "\$plist_app"    2>/dev/null || true
          launchctl unload "\$plist_ollama" 2>/dev/null || true
          ;;
        restart)
          launchctl unload "\$plist_app"    2>/dev/null || true
          launchctl unload "\$plist_ollama" 2>/dev/null || true
          sleep 1
          launchctl load   "\$plist_ollama"
          launchctl load   "\$plist_app"
          ;;
        status)
          launchctl list | grep -E "com.bookmark" || echo "  (not running)"
          ;;
      esac
      ;;
  esac
}

is_running() {
  case "\$OS" in
    linux|wsl) systemctl is-active --quiet bookmark 2>/dev/null ;;
    macos)     launchctl list 2>/dev/null | grep -q "com.bookmark.app" ;;
  esac
}

cmd_start() {
  if is_running; then
    warn "Bookmark is already running."
    return
  fi
  info "Starting Bookmark..."
  service_cmd start
  sleep 2
  if is_running; then
    success "Bookmark is running at http://localhost:\${BOOKMARK_SERVER_PORT:-8080}"
  else
    err "Failed to start. Run 'bookmark logs' to see what went wrong."
  fi
}

cmd_stop() {
  info "Stopping Bookmark..."
  service_cmd stop
  success "Bookmark stopped."
}

cmd_restart() {
  info "Restarting Bookmark..."
  service_cmd restart
  sleep 2
  if is_running; then
    success "Bookmark restarted at http://localhost:\${BOOKMARK_SERVER_PORT:-8080}"
  else
    err "Restart failed. Run 'bookmark logs' to investigate."
  fi
}

cmd_status() {
  echo ""
  echo -e "  \${BOLD}Bookmark Status\${RESET}"
  echo "  ──────────────────────────────────────"
  if is_running; then
    echo -e "  Server   \${GREEN}● running\${RESET}   http://localhost:\${BOOKMARK_SERVER_PORT:-8080}"
  else
    echo -e "  Server   \${RED}○ stopped\${RESET}"
  fi

  if pgrep -x ollama &>/dev/null; then
    echo -e "  Ollama   \${GREEN}● running\${RESET}"
  else
    echo -e "  Ollama   \${RED}○ stopped\${RESET}"
  fi

  if pg_isready -h "\${DB_HOST:-localhost}" -p "\${DB_PORT:-5432}" -q 2>/dev/null; then
    echo -e "  Postgres \${GREEN}● reachable\${RESET}"
  else
    echo -e "  Postgres \${RED}○ unreachable\${RESET}"
  fi
  echo ""

  case "\$OS" in
    linux|wsl)
      echo -e "  \${BOLD}Service details:\${RESET}"
      systemctl status bookmark --no-pager -l 2>/dev/null | tail -12 || true
      ;;
    macos)
      echo -e "  \${BOLD}LaunchAgent details:\${RESET}"
      service_cmd status
      ;;
  esac
  echo ""
}

cmd_logs() {
  local lines="\${2:-50}"
  case "\$OS" in
    linux|wsl)
      journalctl -u bookmark --no-pager -n "\$lines" --output=short-iso
      ;;
    macos)
      echo "=== Bookmark App Log ==="
      tail -n "\$lines" "\$REPO_ROOT/logs/bookmark.log" 2>/dev/null || echo "(no log yet)"
      echo ""
      echo "=== Bookmark Error Log ==="
      tail -n "\$lines" "\$REPO_ROOT/logs/bookmark-error.log" 2>/dev/null || echo "(no errors)"
      ;;
  esac
}

cmd_update() {
  info "Pulling latest changes..."
  cd "\$REPO_ROOT"
  git pull
  source "\$VENV_DIR/bin/activate"
  "$VENV_DIR/bin/pip" install -r requirements.txt --quiet
  python3 manage.py migrate
  if [[ -f frontend/package.json ]]; then
    cd frontend && npm install --silent && PORT=8081 npm run build --silent && cd ..
  fi
  cmd_restart
  success "Bookmark updated."
}

cmd_uninstall() {
  echo ""
  echo -e "  \${RED}\${BOLD}Full Uninstall\${RESET}"
  echo -e "  This will remove EVERYTHING Bookmark installed:"
  echo -e "    • System service (bookmark + bookmark-ollama)"
  echo -e "    • 'bookmark' CLI command"
  echo -e "    • Python virtual environment (.venv/)"
  echo -e "    • Logs (logs/)"
  echo -e "    • Temp captures (tmp/)"
  echo -e "    • .env configuration file"
  echo -e "    • Generated helper files (LOAD_EXTENSION.txt, scripts/)"
  echo -e "    • PostgreSQL database and user"
  echo -e "    \${YELLOW}• Ollama models will NOT be removed (run 'ollama rm <model>' manually)\${RESET}"
  echo -e "    \${YELLOW}• Git repo and your source code will NOT be touched\${RESET}"
  echo ""
  read -rp "  Type 'yes' to confirm full uninstall: " confirm
  [[ "\$confirm" == "yes" ]] || { info "Aborted."; exit 0; }
  echo ""

  # 1. Stop and remove services
  info "Stopping services..."
  service_cmd stop 2>/dev/null || true

  case "\$OS" in
    linux|wsl)
      sudo systemctl disable bookmark 2>/dev/null || true
      sudo systemctl disable bookmark-ollama 2>/dev/null || true
      sudo rm -f /etc/systemd/system/bookmark.service
      sudo rm -f /etc/systemd/system/bookmark-ollama.service
      sudo systemctl daemon-reload
      success "Systemd services removed"
      ;;
    macos)
      launchctl unload "\$HOME/Library/LaunchAgents/com.bookmark.app.plist"    2>/dev/null || true
      launchctl unload "\$HOME/Library/LaunchAgents/com.bookmark.ollama.plist" 2>/dev/null || true
      rm -f "\$HOME/Library/LaunchAgents/com.bookmark.app.plist"
      rm -f "\$HOME/Library/LaunchAgents/com.bookmark.ollama.plist"
      success "LaunchAgents removed"
      ;;
  esac

  # 2. Remove CLI
  sudo rm -f /usr/local/bin/bookmark
  success "CLI removed"

  # 3. Drop PostgreSQL database and user
  info "Dropping PostgreSQL database and user..."
  psql -U postgres -c "DROP DATABASE IF EXISTS \${DB_NAME:-bookmark};" 2>/dev/null     && success "Database '\${DB_NAME:-bookmark}' dropped"     || warn "Could not drop database (may need manual cleanup: psql -U postgres -c \"DROP DATABASE \${DB_NAME:-bookmark};\")"
  psql -U postgres -c "DROP USER IF EXISTS \${DB_USER:-bookmark};" 2>/dev/null     && success "DB user '\${DB_USER:-bookmark}' dropped"     || warn "Could not drop DB user (may need manual cleanup)"

  # 4. Remove Python virtual environment
  if [[ -d "\$REPO_ROOT/.venv" ]]; then
    rm -rf "\$REPO_ROOT/.venv"
    success ".venv/ removed"
  fi

  # 5. Remove logs
  if [[ -d "\$REPO_ROOT/logs" ]]; then
    rm -rf "\$REPO_ROOT/logs"
    success "logs/ removed"
  fi

  # 6. Remove temp captures
  if [[ -d "\$REPO_ROOT/tmp" ]]; then
    rm -rf "\$REPO_ROOT/tmp"
    success "tmp/ removed"
  fi

  # 7. Remove generated scripts folder
  if [[ -d "\$REPO_ROOT/scripts" ]]; then
    rm -rf "\$REPO_ROOT/scripts"
    success "scripts/ removed"
  fi

  # 8. Remove generated helper files
  rm -f "\$REPO_ROOT/LOAD_EXTENSION.txt"
  success "Generated helper files removed"

  # 9. Remove .env last (we needed DB_NAME/DB_USER from it above)
  rm -f "\$REPO_ROOT/.env"
  success ".env removed"

  echo ""
  echo -e "  \${GREEN}\${BOLD}✓ Uninstall complete.\${RESET}"
  echo -e "  Your source code, git history, and Ollama models are untouched."
  echo -e "  To reinstall: \${CYAN}bash install.sh\${RESET}"
  echo ""
}

cmd_help() {
  echo ""
  echo -e "  \${BOLD}bookmark\${RESET} — Local AI Bookmark Intelligence"
  echo ""
  echo -e "  \${BOLD}Usage:\${RESET}  bookmark <command>"
  echo ""
  echo -e "  \${BOLD}Commands:\${RESET}"
  echo -e "    \${CYAN}start\${RESET}       Start Bookmark and Ollama"
  echo -e "    \${CYAN}stop\${RESET}        Stop Bookmark and Ollama"
  echo -e "    \${CYAN}restart\${RESET}     Restart all services"
  echo -e "    \${CYAN}status\${RESET}      Show current service status"
  echo -e "    \${CYAN}logs\${RESET}        Tail the last 50 log lines"
  echo -e "    \${CYAN}logs <n>\${RESET}    Tail the last n log lines"
  echo -e "    \${CYAN}update\${RESET}      Pull latest code and restart"
  echo -e "    \${CYAN}uninstall\${RESET}   Full clean uninstall (removes everything)"
  echo ""
}

# Load .env for DB_HOST etc.
if [[ -f "\$REPO_ROOT/.env" ]]; then
  set -o allexport
  # shellcheck disable=SC1091
  source "\$REPO_ROOT/.env"
  set +o allexport
fi

case "\${1:-help}" in
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  restart)   cmd_restart ;;
  status)    cmd_status ;;
  logs)      cmd_logs "\$@" ;;
  update)    cmd_update ;;
  uninstall) cmd_uninstall ;;
  *)         cmd_help ;;
esac
CLISCRIPT

sudo chmod +x "$CLI_TARGET"
success "CLI installed → you can now run: bookmark start | stop | status | logs"

# ── Final start ───────────────────────────────────────────────────────────────
step "Starting Bookmark"

case "$OS" in
  linux|wsl)
    sudo systemctl start bookmark-ollama 2>/dev/null || true
    sudo systemctl start bookmark
    ;;
  macos)
    launchctl load "$HOME/Library/LaunchAgents/com.bookmark.ollama.plist" 2>/dev/null || true
    launchctl load "$HOME/Library/LaunchAgents/com.bookmark.app.plist"    2>/dev/null || true
    ;;
esac

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}  ✓ Installation complete!${RESET}"
echo ""
echo -e "  ${BOLD}Django API:${RESET}   http://localhost:8080"
echo -e "  ${BOLD}React App:${RESET}    http://localhost:8081"
echo ""
echo -e "  ${BOLD}Useful commands:${RESET}"
echo -e "    ${CYAN}bookmark status${RESET}    — check if everything is running"
echo -e "    ${CYAN}bookmark stop${RESET}      — stop Bookmark and Ollama"
echo -e "    ${CYAN}bookmark start${RESET}     — start them again"
echo -e "    ${CYAN}bookmark logs${RESET}      — tail recent logs"
echo -e "    ${CYAN}bookmark update${RESET}    — pull latest code and restart"
echo -e "    ${CYAN}bookmark uninstall${RESET} — remove service (keeps your data)"
echo ""
echo -e "  ${BOLD}Next steps:${RESET}"
echo -e "    1. Load the Chrome extension — see ${BOLD}LOAD_EXTENSION.txt${RESET} in the repo root"

echo -e "    2. Open ${BOLD}http://localhost:${BOOKMARK_SERVER_PORT:-8080}${RESET} to complete setup"
echo -e "    3. Choose your embedding model — ${YELLOW}this choice is permanent${RESET}"
echo ""