# Generated by Django 5.2.14 on 2026-05-07 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('web', 'Web')], max_length=50)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('post', 'Post'), ('image_page', 'Image Page'), ('web_page', 'Web Page')], max_length=50)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('capture_method', models.CharField(blank=True, choices=[('platform_injection', 'Platform Injection'), ('toolbar_popup', 'Toolbar Popup'), ('context_menu', 'Context Menu')], max_length=50, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('transcript_source', models.CharField(blank=True, choices=[('api', 'YouTube Transcript API'), ('whisper', 'Whisper (local)')], max_length=50, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
    ]
