# Generated by Django 5.2.14 on 2026-05-07 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='BookmarkTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manually Added')], max_length=50)),
                ('bookmark', models.ForeignKey(db_column='bookmark_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookmark')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='core.tags')),
            ],
            options={
                'db_table': 'bookmark_tags',
                'constraints': [models.UniqueConstraint(fields=('bookmark', 'tag'), name='bookmark_tag')],
            },
        ),
    ]
