# Generated by Django 5.2.14 on 2026-05-07 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_config(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO config (id, setup_complete, embedding_locked, server_port) "
            "VALUES (1, false, false, 8080) ON CONFLICT DO NOTHING"
        )
def unseed_config(apps, schema_editor): 
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM config WHERE id = 1;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tags_bookmarktags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('embedding_provider', models.CharField(blank=True, choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('google', 'Google')], max_length=50, null=True)),
                ('embedding_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding_dimensions', models.IntegerField(blank=True, null=True)),
                ('embedding_locked', models.BooleanField(default=False)),
                ('generation_provider', models.CharField(blank=True, choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=20, null=True)),
                ('generation_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('whisper_model_name', models.CharField(blank=True, choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20, null=True)),
                ('setup_complete', models.BooleanField(default=False)),
                ('server_port', models.IntegerField(default=8080)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.RenameModel(
            old_name='BookmarkTags',
            new_name='BookmarkTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('chunk_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('post', 'Post'), ('note', 'Note')], max_length=50)),
                ('chunk_index', models.IntegerField(blank=True, null=True)),
                ('timestamp_seconds', models.IntegerField(blank=True, null=True)),
                ('is_note', models.BooleanField(default=False)),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(db_column='bookmark_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookmark')),
            ],
            options={
                'db_table': 'chunks',
                'ordering': ['chunk_index'],
            },
        ),

        migrations.RunPython(seed_config, reverse_code=unseed_config),
    ]
