# Generated by Django 5.2.14 on 2026-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cleanup_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='failed_at',
            field=models.CharField(choices=[('extraction', 'Extraction'), ('tagging', 'Tagging'), ('chunking', 'Chunking'), ('embedding', 'Embedding')], null=True),
        ),
    ]
