# Generated by Django 5.2.14 on 2026-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bookmark_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dev_mode',
            field=models.BooleanField(default=False),
        ),
    ]
