# Generated by Django 5.2.14 on 2026-05-22 11:47

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_config_dev_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
