# Generated by Django 5.2.14 on 2026-06-22 07:06

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorField
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_chunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="platform_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="chunk",
                    name="embedding",
                    field=VectorField(
                        dimensions=768,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="config",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
