# Generated by Django 5.2.14 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_bookmark_platform_metadata_chunk_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="content_type",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="has_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="has_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="has_video",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="raw_text",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="raw_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="failed_at",
            field=models.CharField(
                choices=[
                    ("extraction", "Extraction"),
                    ("tagging", "Tagging"),
                    ("chunking", "Chunking"),
                    ("embedding", "Embedding"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
