# Generated by Django 5.2.14 on 2026-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookmark_modality_flags_and_json_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='current_step',
            field=models.CharField(blank=True, choices=[('extraction', 'Extraction'), ('tagging', 'Tagging'), ('chunking', 'Chunking'), ('embedding', 'Embedding')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE bookmarks ADD CONSTRAINT current_step_check "
                "CHECK (current_step IN ('extraction', 'tagging', 'chunking', 'embedding'));",
            reverse_sql="ALTER TABLE bookmarks DROP CONSTRAINT current_step_check;",
        ),
    ]
