# Generated by Django 5.2.14 on 2026-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_current_step_and_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
