# Generated by Django 5.2.14 on 2026-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_highlight_and_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='chunk_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('post', 'Post'), ('highlight', 'Highlight'), ('screenshot', 'Screenshot'), ('note', 'Note'), ('metadata', 'Metadata')], max_length=50),
        ),
    ]
