# Generated by Django 5.2.14 on 2026-07-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_repair_unembedded_complete_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working')], default='idle', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bookmark')),
            ],
            options={
                'db_table': 'worker_status',
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE worker_status SET UNLOGGED;",
            reverse_sql="ALTER TABLE worker_status SET LOGGED;",
        ),
    ]
